import type { Metadata } from 'next';
import {notFound} from 'next/navigation';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { getMessages, getTranslations } from 'next-intl/server';
import NextAuthSessionProviderWrapper from '@/lib/next-auth/components/NextAuthSessionProviderWrapper';
import { ThemeProvider } from '@/components/theme/ThemeProvider';
import { Content, Wrapper } from '@/components/layout';
import { MobileSidebarProvider } from '@/components/layout/MobileSidebarContext';
import {routing} from '@/i18n/routing';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  await getTranslations({ locale: locale, namespace: 'common' });

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <NextAuthSessionProviderWrapper>
            <ThemeProvider>
              <MobileSidebarProvider>
                <Wrapper>
                  <Content>
                    {children}
                  </Content>
                </Wrapper>
              </MobileSidebarProvider>
            </ThemeProvider>
          </NextAuthSessionProviderWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
